// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaW4hT9xVWAyUbcXogu1VN3CxwfK_d214',
    appId: '1:179007834178:web:739fb8f0eca953815985db',
    messagingSenderId: '179007834178',
    projectId: 'nmtc-hackathon-status',
    authDomain: 'nmtc-hackathon-status.firebaseapp.com',
    databaseURL: 'https://nmtc-hackathon-status-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nmtc-hackathon-status.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYxkuorqjEQCk6NryITx56KtCZAc0pi9k',
    appId: '1:179007834178:android:74442b14c105c1125985db',
    messagingSenderId: '179007834178',
    projectId: 'nmtc-hackathon-status',
    databaseURL: 'https://nmtc-hackathon-status-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nmtc-hackathon-status.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC92HIeVuf92HHdVeJVDOgvCUsYIAi3A_w',
    appId: '1:179007834178:ios:9e56142abac771945985db',
    messagingSenderId: '179007834178',
    projectId: 'nmtc-hackathon-status',
    databaseURL: 'https://nmtc-hackathon-status-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nmtc-hackathon-status.appspot.com',
    iosBundleId: 'com.omar.nmtc.nmtcHackathonStatus',
  );
}
